import { formatToDateString } from "./helpers.js"

 export const data = [
    {
      sn: 1,
      description: 'do some shopping at maxland shopping mall',
      status: 'Done',
      date: new Date('2023-11-11'),
      priority: 'High',
    },
    {
      id: Math.random(),
      description: 'fill my 12.5kg gas',
      status: 'in progress',
      date:new Date('2020-09-20'),
      priority: 'Low',
    },
    {
      id: Math.random(),
      description: 'hang out with friends for about 1hr',
      status: 'todo',
      date: new Date('2022-10-11'),
      priority: 'Medium',
    },
    {
      id: Math.random(),
      description: 'cut my hair',
      status: 'todo',
      date: new Date('2021-07-28'),
      priority: 'High',
    },
    {
      id: Math.random(),
      description: 'refill my car fuel tank',
      status: 'in progress',
      date: new Date('2022-10-11'),
      priority: 'High',
    },
    {
      id: Math.random(),
      description: 'work on my project',
      status: 'in progress',
      date: new Date('2024-10-11'),
      priority: 'Low',
    },
    {
      id: Math.random(),
      description: 'spend some time with friends',
      status: 'Done',
      date: new Date('2021-07-28'),
      priority: 'Low',
    },
    {
      sn: 1,
      description: 'do some shopping at maxland shopping mall',
      status: 'Done',
      date:new Date('2001-10-12'),
      priority: 'High',
    },
    {
      id: Math.random(),
      description: 'fill my 12.5kg gas',
      status: 'in progress',
      date:new Date('2009-07-14'),
      priority: 'Low',
    },
    {
      id: Math.random(),
      description: 'hang out with friends for about 1hr',
      status: 'todo',
      date: new Date('2023-04-05'),
      priority: 'Medium',
    },
    {
      id: Math.random(),
      description: 'cut my hair',
      status: 'todo',
      date:new Date('2022-04-05'),
      priority: 'High',
    },
    {
      id: Math.random(),
      description: 'refill my car fuel tank',
      status: 'in progress',
      date: new Date('2021-04-05'),
      priority: 'High',
    },
    {
      id: Math.random(),
      description: 'work on my project',
      status: 'in progress',
      date: new Date('2023-05-06'),
      priority: 'Low',
    },
    {
      id: Math.random(),
      description: 'spend some time with friends',
      status: 'Done',
      date: new Date('2023-06-07'),
      priority: 'Low',
    },
    {
      sn: 1,
      description: 'do some shopping at maxland shopping mall',
      status: 'Done',
      date: new Date('2023-07-08'),
      priority: 'High',
    },
    {
      id: Math.random(),
      description: 'fill my 12.5kg gas',
      status: 'in progress',
      date:new Date('2017-03-03'),
      priority: 'Low',
    },
    {
      id: Math.random(),
      description: 'hang out with friends for about 1hr',
      status: 'todo',
      date:new Date('2023-08-09'),
      priority: 'Medium',
    },
    {
      id: Math.random(),
      description: 'cut my hair',
      status: 'todo',
      date:  new Date('2023-09-10'),
      priority: 'High',
    },
    {
      id: Math.random(),
      description: 'refill my car fuel tank',
      status: 'in progress',
      date: new Date('2023-10-11'),
      priority: 'High',
    },
    {
      id: Math.random(),
      description: 'work on my project',
      status: 'in progress',
      date:new Date('2023-11-12'),
      priority: 'Low',
    },
    {
      id: Math.random(),
      description: 'spend some time with friends',
      status: 'Done',
      date: new Date('2023-12-12'),
      priority: 'Low',
    },
    {
      id: Math.random(),
      description: 'spend some time with friends',
      status: 'Done',
      date: new Date('2013-05-06'),
      priority: 'Low',
    },
    {
      sn: 1,
      description: 'do some shopping at maxland shopping mall',
      status: 'Done',
      date: new Date('2014-05-06'),
      priority: 'High',
    },
    {
      id: Math.random(),
      description: 'fill my 12.5kg gas',
      status: 'in progress',
      date:new Date('2016-05-06'),
      priority: 'Low',
    },
    {
      id: Math.random(),
      description: 'cut my hair',
      status: 'todo',
      date: new Date('2017-05-06'),
      priority: 'High',
    },
    {
      id: Math.random(),
      description: 'refill my car fuel tank',
      status: 'in progress',
      date: new Date('2016-05-06'),
      priority: 'High',
    },
    {
      id: Math.random(),
      description: 'work on my project',
      status: 'in progress',
      date:new Date('2015-05-06'),
      priority: 'Low',
    },
    {
      id: Math.random(),
      description: 'spend some time with friends',
      status: 'Done',
      date:new Date('2023-07-08'),
      priority: 'Low',
    },
    {
      id: Math.random(),
      description: 'refill my car fuel tank',
      status: 'in progress',
      date: new Date('2023-10-11'),
      priority: 'High',
    },
    {
      id: Math.random(),
      description: 'work on my project',
      status: 'in progress',
      date: new Date('2023-11-12'),
      priority: 'Low',
    },
    {
      id: Math.random(),
      description: 'spend some time with friends',
      status: 'Done',
      date:new Date('2023-12-12'),
      priority: 'Low',
    },
    {
      id: Math.random(),
      description: 'cut my hair',
      status: 'todo',
      date:new Date('2023-05-06'),
      priority: 'High',
    },
    {
      id: Math.random(),
      description: 'refill my car fuel tank',
      status: 'in progress',
      date: new Date('2020-05-06'),
      priority: 'High',
    },
    {
      id: Math.random(),
      description: 'work on my project',
      status: 'in progress',
      date: new Date('2012-05-06'),
      priority: 'Low',
    },
    {
      id: Math.random(),
      description: 'spend some time with friends',
      status: 'Done',
      date: new Date('2013-05-06'),
      priority: 'Low',
    },
    {
      sn: 1,
      description: 'do some shopping at maxland shopping mall',
      status: 'Done',
      date: new Date('2014-05-06'),
      priority: 'High',
    },
    {
      id: Math.random(),
      description: 'fill my 12.5kg gas',
      status: 'in progress',
      date:new Date('2016-05-06'),
      priority: 'Low',
    },
    {
      sn: 1,
      description: 'do some shopping at maxland shopping mall',
      status: 'Done',
      date: new Date('2001-10-12'),
      priority: 'High',
    },
    {
      id: Math.random(),
      description: 'fill my 12.5kg gas',
      status: 'in progress',
      date:new Date('2009-07-14'),
      priority: 'Low',
    },
    {
      id: Math.random(),
      description: 'hang out with friends for about 1hr',
      status: 'todo',
      date:new Date('2023-04-05'),
      priority: 'Medium',
    },
    {
      id: Math.random(),
      description: 'cut my hair',
      status: 'todo',
      date:new Date('2022-04-05'),
      priority: 'High',
    },
    {
      id: Math.random(),
      description: 'refill my car fuel tank',
      status: 'in progress',
      date: new Date('2021-04-05'),
      priority: 'High',
    },
    {
      sn: 1,
      description: 'do some shopping at maxland shopping mall',
      status: 'Done',
      date: new Date('2019-02-01'),
      priority: 'High',
    },
    {
      id: Math.random(),
      description: 'fill my 12.5kg gas',
      status: 'in progress',
      date:new Date('2023-04-05'),
      priority: 'Low',
    },
    {
      id: Math.random(),
      description: 'hang out with friends for about 1hr',
      status: 'todo',
      date: new Date('2023-05-06'),
      priority: 'Medium',
    },
    {
      id: Math.random(),
      description: 'cut my hair',
      status: 'todo',
      date:new Date('2023-05-06'),
      priority: 'High',
    },
    {
      id: Math.random(),
      description: 'refill my car fuel tank',
      status: 'in progress',
      date:new Date('2023-05-06'),
      priority: 'High',
    },
    {
      id: Math.random(),
      description: 'work on my project',
      status: 'in progress',
      date: new Date('2023-05-06'),
      priority: 'Low',
    },
    {
      id: Math.random(),
      description: 'spend some time with friends',
      status: 'Done',
      date: new Date('2023-05-06'),
      priority: 'Low',
    },
    {
      id: Math.random(),
      description: 'fill my 12.5kg gas',
      status: 'in progress',
      date:new Date('2023-05-06'),
      priority: 'Low',
    },
  ];