const data = [
    {
      sn: math.random(),
      description: 'do some shopping at maxland shopping mall',
      status: 'Done',
      date: getCurrentDate(),
      priority: 'High',
    },
    {
      id: Math.random(),
      description: 'fill my 12.5kg gas',
      status: 'in progress',
      date: getCurrentDate(),
      priority: 'Low',
    },
    {
      id: Math.random(),
      description: 'hang out with friends for about 1hr',
      status: 'todo',
      date: getCurrentDate(),
      priority: 'Medium',
    },
    {
      id: Math.random(),
      description: 'cut my hair',
      status: 'todo',
      date: getCurrentDate(),
      priority: 'High',
    },
    {
      id: Math.random(),
      description: 'refill my car fuel tank',
      status: 'in progress',
      date: getCurrentDate(),
      priority: 'High',
    },
    {
      id: Math.random(),
      description: 'work on my project',
      status: 'in progress',
      date: getCurrentDate(),
      priority: 'Low',
    },
    {
      id: Math.random(),
      description: 'spend some time with friends',
      status: 'Done',
      date: getCurrentDate(),
      priority: 'Low',
    },
  ];